/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "tertiary-fixed": "#d5dffd",
              "on-background": "#2b3437",
              "surface-variant": "#dbe4e7",
              "surface-dim": "#d1dce0",
              "on-secondary-container": "#40555f",
              "on-error-container": "#782232",
              "tertiary-fixed-dim": "#c7d1ee",
              "on-surface": "#2b3437",
              "surface": "#f8f9fa",
              "inverse-on-surface": "#9b9d9e",
              "on-primary-fixed-variant": "#4953ac",
              "on-primary-container": "#3f48a1",
              "error-container": "#ff8b9a",
              "on-secondary-fixed-variant": "#495f69",
              "on-tertiary-fixed": "#333d55",
              "background": "#f8f9fa",
              "on-primary-fixed": "#2c358e",
              "surface-container-lowest": "#ffffff",
              "tertiary-container": "#d5dffd",
              "on-tertiary": "#f9f8ff",
              "on-secondary": "#f2faff",
              "primary": "#4c56af",
              "surface-container-high": "#e3e9ec",
              "primary-fixed": "#e0e0ff",
              "surface-container-highest": "#dbe4e7",
              "on-secondary-fixed": "#2d424c",
              "on-tertiary-fixed-variant": "#4f5a72",
              "on-error": "#fff7f7",
              "outline-variant": "#abb3b7",
              "surface-tint": "#4c56af",
              "secondary-fixed-dim": "#c1d8e4",
              "surface-container": "#eaeff1",
              "inverse-surface": "#0c0f10",
              "secondary-dim": "#415660",
              "secondary-container": "#cfe6f2",
              "outline": "#737c7f",
              "surface-container-low": "#f1f4f6",
              "primary-fixed-dim": "#ced1ff",
              "on-surface-variant": "#586064",
              "primary-container": "#e0e0ff",
              "on-tertiary-container": "#455068",
              "primary-dim": "#4049a2",
              "secondary": "#4d626c",
              "secondary-fixed": "#cfe6f2",
              "tertiary": "#545f78",
              "error": "#9e3f4e",
              "tertiary-dim": "#49536b",
              "on-primary": "#f9f6ff",
              "inverse-primary": "#929bfa",
              "error-dim": "#4f0116",
              "surface-bright": "#f8f9fa"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "fontFamily": {
              "headline": ["Inter"],
              "body": ["Inter"],
              "label": ["Inter"],
              "mono": ['"JetBrains Mono"', "ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace"]
      }
    },
  },
}
